project_name: adguard-exporter
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
archives:
  - format: tar.gz
checksum:
  name_template: 'checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/vtmocanu/adguard-exporter:{{ .Tag }}-amd64
      - ghcr.io/vtmocanu/adguard-exporter:latest-amd64
  - goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/vtmocanu/adguard-exporter:{{ .Tag }}-arm64v8
      - ghcr.io/vtmocanu/adguard-exporter:latest-arm64v8
docker_manifests:
  - name_template: ghcr.io/vtmocanu/adguard-exporter:{{ .Tag }}
    image_templates:
      - ghcr.io/vtmocanu/adguard-exporter:{{ .Tag }}-amd64
      - ghcr.io/vtmocanu/adguard-exporter:{{ .Tag }}-arm64v8
  - name_template: ghcr.io/vtmocanu/adguard-exporter:latest
    image_templates:
      - ghcr.io/vtmocanu/adguard-exporter:latest-amd64
      - ghcr.io/vtmocanu/adguard-exporter:latest-arm64v8
